//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wordiny.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wordiny.Api.Resources.BotMessages", typeof(BotMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какой перевод для «{0}»?
        ///(Если передумал, нажми «Отменить ввод ❌» снизу.)
        ///&lt;keyboard reply&gt;
        ///&lt;button text=&quot;Отменить ввод ❌&quot;&gt;
        ///&lt;/keyboard&gt;.
        /// </summary>
        public static string AwaitingWordTranslation {
            get {
                return ResourceManager.GetString("AwaitingWordTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ввод отменён
        ///&lt;keyboard reply_remove&gt;&lt;/keyboard&gt;.
        /// </summary>
        public static string AwaitingWordTranslation_Cancel {
            get {
                return ResourceManager.GetString("AwaitingWordTranslation_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавил: {0} — {1}.
        ///Присылай следующее слово или напиши /help, чтобы посмотреть команды.
        ///&lt;keyboard reply_remove&gt;&lt;/keyboard&gt;.
        /// </summary>
        public static string AwaitingWordTranslation_Complete {
            get {
                return ResourceManager.GetString("AwaitingWordTranslation_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нашёл часовой пояс: {0}. Всё верно?
        ///&lt;keyboard reply&gt;
        ///&lt;button text=&quot;Да&quot;&gt;
        ///&lt;button text=&quot;Нет&quot;&gt;
        ///&lt;/keyboard&gt;.
        /// </summary>
        public static string ConfirmTimeZone {
            get {
                return ResourceManager.GetString("ConfirmTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш часовой пояс обнаружен правильно?.
        /// </summary>
        public static string ConfirmTimeZone_InvalidInput {
            get {
                return ResourceManager.GetString("ConfirmTimeZone_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Готово! Теперь можешь прислать первое слово или фразу
        ///
        ///Например, попробуй написать hello (это означает привет)
        ///&lt;keyboard reply_remove&gt;&lt;/keyboard&gt;.
        /// </summary>
        public static string SetupFinished {
            get {
                return ResourceManager.GetString("SetupFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сколько уведомлений в день присылать?
        ///&lt;keyboard reply&gt;
        ///&lt;button text=&quot;2&quot;&gt;
        ///&lt;button text=&quot;3&quot;&gt;
        ///&lt;row&gt;
        ///&lt;button text=&quot;4&quot;&gt;
        ///&lt;button text=&quot;5&quot;&gt;
        ///&lt;/keyboard&gt;.
        /// </summary>
        public static string SetupFrequency {
            get {
                return ResourceManager.GetString("SetupFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество уведомлений в день может быть от 2 до 5 включительно.
        /// </summary>
        public static string SetupFrequency_InvalidInput {
            get {
                return ResourceManager.GetString("SetupFrequency_InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чтобы не писать тебе ночью, нужен твой часовой пояс. Отправь геолокацию кнопкой ниже
        ///&lt;keyboard reply&gt;
        ///&lt;button text=&quot;Отправить геолокацию 📍&quot; request_location&gt;
        ///&lt;/keyboard&gt;.
        /// </summary>
        public static string SetupTimeZone {
            get {
                return ResourceManager.GetString("SetupTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не смог найти часовой пояс по твоей геолокации. Пожалуйста, попробуй ещё раз позже.
        /// </summary>
        public static string SetupTimeZone_Failed {
            get {
                return ResourceManager.GetString("SetupTimeZone_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пожалуйста, отправь свою геолокацию через кнопку внизу.
        /// </summary>
        public static string SetupTimeZone_InvalidLocation {
            get {
                return ResourceManager.GetString("SetupTimeZone_InvalidLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Что-то пошло не так :(
        ///
        ///Попробуй ещё раз попозже.
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С возвращением!.
        /// </summary>
        public static string UserReturn {
            get {
                return ResourceManager.GetString("UserReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привет! Помогу учить иностранные слова и фразы, которые ты добавишь
        ///
        ///Ты добавляешь слово и его перевод, а я несколько раз в день присылаю тебе уведомление с одним из них, чтобы они лучше откладывались в памяти
        ///
        ///Давай сначала узнаем где ты и сколько уведомлений в день ты готов видеть.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
